name: Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Release artifacts to Bintray, Maven Central & SDKMAN, and publish documentation
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: puneetbehl
      GIT_USER_EMAIL: behlp@objectcomputing.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Set the current release version
        id: release_version
        run: echo ::set-output name=release_version::${GITHUB_REF:11}
      - name: Run pre-release
        uses: micronaut-projects/github-actions/pre-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build All
        run: ./gradlew grails-cli:assemble
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      - name: Generate secring file
        env:
          SECRING_FILE: ${{ secrets.SECRING_FILE }}
        run: echo $SECRING_FILE | base64 -d > ${{ github.workspace }}/secring.gpg
      - name: Publish to Maven Central
        uses: gradle/gradle-build-action@v2
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_NEXUS_URL: ${{ secrets.SONATYPE_NEXUS_URL }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          SECRING_FILE: ${{ secrets.SECRING_FILE }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        with:
          arguments: -Psigning.secretKeyRingFile=${{ github.workspace }}/secring.gpg publishToSonatype closeAndReleaseSonatypeStagingRepository docs
      - name: Upload CLI Zip
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: grails-cli/build/distributions/grails-cli-${{ steps.release_version.outputs.release_version }}.zip
          asset_name: grails-cli-${{ steps.release_version.outputs.release_version }}.zip
          asset_content_type: application/zip
      - name: Publish to Github Pages
        if: success()
        uses: micronaut-projects/github-pages-deploy-action@master
        env:
          BETA: ${{ contains(steps.release_version.outputs.release_version, 'M') || contains(steps.release_version.outputs.release_version, 'RC') }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build/docs
          VERSION: ${{ steps.release_version.outputs.release_version }}
      - name: Run post-release
        if: success()
        id: post_release
        continue-on-error: true
        uses: micronaut-projects/github-actions/post-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Back to snapshot
        continue-on-error: true
        run: |
          echo "Setting new Grails snapshot version"
          sed -i "s/^grailsVersion.*$/grailsVersion\=${{ steps.post_release.outputs.next_version }}-SNAPSHOT/" gradle.properties
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        continue-on-error: true
        with:
          commit_message: Back Grails version to snapshot
          commit_user_name: ${{ env.GIT_USER_NAME }}
          commit_user_email: ${{ env.GIT_USER_EMAIL }}
          commit_author: ${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>
          file_pattern: gradle.properties
  linux:
    name: Release Linux Native CLI
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set the current release version
        id: release_version
        run: |
          release_version=${GITHUB_REF:11}
          sed -i "s/^projectVersion.*$/projectVersion\=${release_version}/" gradle.properties
          echo ::set-output name=release_version::${release_version}
      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the JAR
        uses: gradle/gradle-build-action@v2
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        with:
          arguments: grails-cli:shadowJar --no-daemon
      - name: Build Native Image
        run: native-image --no-fallback --allow-incomplete-classpath -cp grails-cli/build/libs/grails-cli-*-all.jar
      - name: Verify Build
        run: ./grails --version
      - name: Package Build
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          mkdir -p "grails-linux-amd64-${VERSION}/bin"
          mv ./grails "grails-linux-amd64-${VERSION}/bin"
          cp ./LICENSE "grails-linux-amd64-${VERSION}/"
          zip -r "grails-linux-amd64-${VERSION}.zip" "grails-linux-amd64-${VERSION}/"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./grails-linux-amd64-${{ github.event.release.tag_name }}.zip
          asset_name: grails-linux-amd64-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
  macos:
    name: Release OS X Native CLI
    runs-on: macos-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set the current release version
        id: release_version
        run: |
          release_version=${GITHUB_REF:11}
          sed -i -e "s/^projectVersion.*$/projectVersion\=${release_version}/" gradle.properties
          echo ::set-output name=release_version::${release_version}
      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the JAR
        uses: gradle/gradle-build-action@v2
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        with:
          arguments: grails-cli:shadowJar --no-daemon
      - name: Build Native Image
        run: native-image --no-fallback --allow-incomplete-classpath -cp grails-cli/build/libs/grails-cli-*-all.jar
      - name: Verify Build
        run: ./grails --version
      - name: Package Build
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          mkdir -p "grails-darwin-amd64-${VERSION}/bin"
          mv ./grails "grails-darwin-amd64-${VERSION}/bin"
          cp ./LICENSE "grails-darwin-amd64-${VERSION}/"
          zip -r "grails-darwin-amd64-${VERSION}.zip" "grails-darwin-amd64-${VERSION}/" -x '*.DS_Store*' -x '__MAC_OSX'
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./grails-darwin-amd64-${{ github.event.release.tag_name }}.zip
          asset_name: grails-darwin-amd64-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
  windows:
    name: Release Windows Native CLI
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build JAR File
        uses: gradle/gradle-build-action@v2
        shell: powershell
        with:
          arguments: grails-cli:copyShadowJar --no-daemon
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      - name: Build Native Image
        shell: powershell
        run: native-image.cmd --no-fallback --allow-incomplete-classpath -cp build/libs/cli.jar
      - name: Verify Build (Powershell)
        run: ./grails.exe --version
      - name: Verify Create App (Powershell)
        run: ./grails.exe create-app test
      - name: Verify Build (CMD)
        shell: cmd
        run: grails --version
      - name: Verify Create App (CMD)
        shell: cmd
        run: grails create-app test2
      - name: ZIP Archive
        run: |
          New-Item ./grails-win-amd64-${{ github.event.release.tag_name }}/bin -ItemType Directory -ea 0
          Move-Item -Path ./grails.exe -Destination ./grails-win-amd64-${{ github.event.release.tag_name }}/bin
          Copy-Item ./LICENSE -Destination ./grails-win-amd64-${{ github.event.release.tag_name }}
          Compress-Archive -Path ./grails-win-amd64-${{ github.event.release.tag_name }} -Update -DestinationPath ./grails-win-amd64-${{ github.event.release.tag_name }}.zip
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./grails-win-amd64-${{ github.event.release.tag_name }}.zip
          asset_name: grails-win-amd64-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
  sdkman:
    name: Release to SDKMAN!
    runs-on: ubuntu-latest
    needs: [linux, macos, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set the current release version
        id: release_version
        run: |
          release_version=${GITHUB_REF:11}
          sed -i "s/^projectVersion.*$/projectVersion\=${release_version}/" gradle.properties
          echo ::set-output name=release_version::${release_version}
      - name: Grails SDK Minor Release
        if: (startsWith(steps.release_version.outputs.release_version, '3.3') || startsWith(steps.release_version.outputs.release_version, '4.1.') ||  contains(steps.release_version.outputs.release_version, 'M') || contains(steps.release_version.outputs.release_version, 'RC'))
        uses: gradle/gradle-build-action@v2
        with:
          arguments: sdkMinorRelease
        env:
          GVM_SDKVENDOR_KEY: ${{ secrets.GVM_SDKVENDOR_KEY }}
          GVM_SDKVENDOR_TOKEN: ${{ secrets.GVM_SDKVENDOR_TOKEN }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      - name: Grails SDK Major Release
        if: !(startsWith(steps.release_version.outputs.release_version, '3.3') || startsWith(steps.release_version.outputs.release_version, '4.1.') || contains(steps.release_version.outputs.release_version, 'M') || contains(steps.release_version.outputs.release_version, 'RC'))
        uses: gradle/gradle-build-action@v2
        with:
          arguments: sdkMajorRelease
        env:
          GVM_SDKVENDOR_KEY: ${{ secrets.GVM_SDKVENDOR_KEY }}
          GVM_SDKVENDOR_TOKEN: ${{ secrets.GVM_SDKVENDOR_TOKEN }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
